### ISSUE TITLE
Missing PSR Message Interface Dependency?

### ISSUE THREAD

**Issue by vlucas** [relayphp/Relay.Relay#1]
This code references interfaces in the `Psr` namespace, but the package `psr/http-message` is not included in composer. How are these interfaces being loaded?

**Comment by pmjones** [comment]
(/me facepalm)

Fixed now. FWIW they loaded up as a dev dependency on Diactoros, but of course that would not work in a non-dev situation. Thanks!

**Comment by vlucas** [comment]
I figured they were a part of the dev dependencies - thanks for the quick fix :)

**Comment by pmjones** [comment]
Sure thing man -- thanks for the quick eyes. :-)
