### ISSUE TITLE
Error Handler Support

### ISSUE THREAD

**Issue by spiffyjr** [relayphp/Relay.Relay#11]
Error handlers are middleware with an arity of four and can be invoked by adding a third argument to the `$next` call.

Invoking an error:

```
$next($request, $response, 'error occurred');
```

Middleware signature:

```
function($error, $request, $response, $next)
```

What's nice about error handlers is that when an error is invokved (via an exception, or a call to next with three arguments) you can go through the error handler queue and have a logger, maybe an error page render, etc.

Any plans on implementing something similar to Relay?

**Comment by pmjones** [comment]
> Any plans on implementing something similar to Relay?

I know that Sencha Connect (originally) and Stratigility (by porting) do that, but even so, I had not intended on adding it. I have found it pretty straightforward to add an exception-handler middleware at or near the top of the queue. Cf. https://github.com/relayphp/Relay.Middleware#exceptionhandler. That acts as a final fallback for uncaught exceptions; it's the place where one can "have a logger, maybe an error page render, etc." As such, having a special middleware signature specifically for error conditions doesn't really seem _necessary_ to me, and not even especially convenient, even in the mid-term.

I'm interested to hear about what I might be missing, though, and I reserve the right to modify Relay based on new information. ;-)

**Comment by spiffyjr** [comment]
In your ExceptionHandler middleware you catch exceptions, which is fine, but what about chaining the error handlers? The next middleware in the stack has no idea that the request/response it's receiving is an error unless you specifically tell it. i.e.., setting an attribute on the request or some other method.

If you were to implement, say, ErrorLogHandler after your ExceptionHandler how would you do it? 

```
// exception handler
$request = $request->withAttribute('exception', $ex);

// error log handler
if (isset($request->getAttributes('exception'))) { ... }
```

Using a four arity signature makes this very clear in the implementation. There's no guess work and no passing along information. It also provides a standard on how error handler middleware should work which makes them more reusable across frameworks.

My 2c.

**Comment by pmjones** [comment]
I've been thinking about this, and I'm still at a loss. Maybe it's because I don't expect the majority of the application to be in middleware, and for most middleware to be in classes (not closures).

> If you were to implement, say, ErrorLogHandler after your ExceptionHandler how would you do it?

I'd create an ExceptionHandler that uses a log dependency to do the logging.

(/me thinks)

I suppose what you're getting at is that you want to wrap error handling the same way that you wrap request/response handling. But they have different responsibilities, so they need different signatures to be recognizable from each other within the same queue of middleware. Is that right?

Perhaps what's really needed here is an ExceptionHandler with its own injected Relay queue, through which errors can be handled. You would add error-handling middleware to that queue, the same way you add "normal" request/response middleware to the "normal" queue. But then what handles errors in the error handling queue? Etc etc.

**Comment by spiffyjr** [comment]
A super simple use-case would be an error handler that renders a template using plates and a separate one for using logging. Sure, you could combine them, but then you have a template dependency on a logger that doesn't need it. For your normal site you'd want both handlers but for APIs you only want the logging and maybe another handler for rendering JSON errors.

An exception handler with an internal queue could accomplish the same thing but might give you a bit less flexibility on where in the stack you want it.

Additionally, Stratigility has a "FinalHandler" that runs if any stack (error or regular) is exhausted. This ensure you always have a fallback handler. That's an implementation detail best left to the user, imo. I guess you could argue an error handler is an implementation detail best left to the user.

**Comment by mindplay-dk** [comment]
@pmjones 

> I have found it pretty straightforward to add an exception-handler middleware at or near the top of the queue

+1 for giving us the choice of installing error-handling if we want it. The built-in error handling in zend-stratigility has tripped us up and cost us a lot of hours.

IMO, there's no reason any component should have built-in error-handling or `try { .. } catch (Exception $e) { ... }` which makes it really difficult to debug anything. Once you start doing global error handling, you're building a framework, not a component - we're considering Relay as a component in our stack, not as our framework, and this is a big factor for us.

**Comment by mindplay-dk** [comment]
> Additionally, Stratigility has a "FinalHandler" that runs if any stack (error or regular) is exhausted. This ensure you always have a fallback handler. That's an implementation detail best left to the user, imo

+1 for that, this tripped us up as well. The idea of "FinalHandler" as a finite concept doesn't even make any sense to me - the final handler is simply the handler at the bottom of the stack; what that is should be your own choice, it doesn't need special privileges or handling.

**Comment by spiffyjr** [comment]
I think there's enough discussion on this to consider it closed. After spending more time with it I see no reason to have an error and/or FinalHandler.

**Comment by pmjones** [comment]
@spiffyjr Good to hear.
