### ISSUE TITLE
Why __invoke() in Runner?

### ISSUE THREAD

**Issue by mindplay-dk** [relayphp/Relay.Relay#12]
Why does `Relay` itself [implement](https://github.com/relayphp/Relay.Relay/blob/1.x/src/Relay.php#L59) `__invoke()`?

That seems unnecessary and I found it pretty confusing - it's not middleware, correct? I think a real method would make more sense - the convention is for middleware to be implemented as callable objects, so it's a bit misleading that the `Relay` class itself is built this way.

Also, `__invoke()` has poor IDE support, and you don't get auto-completion or argument checks.

IMO, this looks odd:

``` php
$relay = $relayBuilder->newInstance($queue);
$response = $relay($request, $response); // huh?
```

It's not obvious what happens there - `$relay->dispatch($request, $response)` would be a lot more obvious, as clearly the middleware is being dispatched.

I know that's a BC break, so I would propose you preserve both options, also for those who love to write PHP that looks like Javascript, e.g. not me ;-)

**Comment by pmjones** [comment]
Hi @mindplay-dk -- I've thought about this a little while now.

> Why does Relay itself implement __invoke()?

Over the past couple of years, I have leaned in the direction that if there is a single public method on an object, that method should probably be __invoke(). That's a rule-of-thumb for me and not a law, obviously.

> __invoke() has poor IDE support, and you don't get auto-completion or argument checks.

However, your comment about IDE completion is well-taken. I'm not generally an IDE fan but I know a lot of folks are. Perhaps adding $relay->relay($request, $response) and $runner->run($request, $response) are in order, or dispatch() methods for both in addition to the __invoke().

BC breaks are not necessarily a big deal yet, as there has been no stable release, but a deprecation period before removal (if they ever get removed) would be reasonable.

Further thoughts?

**Comment by mindplay-dk** [comment]
> I have leaned in the direction that if there is a single public method on an object, that method should probably be __invoke()

Yikes. I mean, if everyone followed that rule, code would generally be totally unreadable ;-)

Lots of classes start out with one public method and end up with two - so for one, you're creating a really destructive refactoring path that way.

Also, when it comes to interfaces, they generally describe a facet - and you can't know that somebody else's object has only one facet. 

IMO, you need to revise your thinking there. `__invoke()` is for situations where you want to allow both anonymous stateless functions and named (stateful) objects to be useable. It's not a means of avoiding method names - which add semantic information at call sites. I reckon that's a good thing :-)

On naming, I'd suggest `dispatch()` for Relay, since it's described as a "middleware dispatcher".

I'm very surprised to learn that you don't use an IDE - you must be meticulous? I can normally tell (very easily) if somebody is coding without tools ;-)

**Comment by pmjones** [comment]
> you must be meticulous?

Very.

> I'd suggest dispatch() for Relay

And for Runner?

**Comment by mindplay-dk** [comment]
> And for Runner?

`run()`? :-)

**Comment by pmjones** [comment]
I get where you're coming from, and I appreciate your previous (and excellent) work in Aura.SqlQuery et al., but after much consideration, I'm going to decline this change. I hope it doesn't cause too much trouble for you, and thanks for bringing it up in the first place.

**Comment by mindplay-dk** [comment]
> I'm going to decline this change

On what grounds, I wonder? (You could maintain `__invoke()` for backwards compatibility.)

Either way, IDE support is a code standard requirement where I work, so I have to work around that.

I really don't want to write code like `->__invoke(..)` since `__invoke` is an implementation detail.

Which would you recommend, forking or extending the project? (looks like dependency injection everywhere, so I should be able to extend everything and add the necessary API methods?)
