### ISSUE TITLE
RequestInterface vs. ServerRequestInterface

### ISSUE THREAD

**Issue by ppetermann** [relayphp/Relay.Relay#15]
I just noticed that Relay seems to be using \Psr\Http\Message\RequestInterface, and was wondering why, as in my opinion for Middleware the \Psr\Http\Message\ServerRequestInterface would be a better fit?

**Comment by elazar** [comment]
I suspect because that would limit the potential applications. Even though it would likely be the less common use case, it's possible to use Relay to apply and dispatch a request from an HTTP client, versus using it to dispatch incoming application requests.

**Comment by pmjones** [comment]
@elazar has it right. The earliest version was ServerRequest interface, but then @oscarotero in #5  remarked that having "client-side use" would be valuable, with little or no negative effect to "server-side use". I agreed, and so we have both client- and server-side capability now.
