### ISSUE TITLE
Why have  you created Relay when Stratigility already does the same thing?

### ISSUE THREAD

**Issue by claudio-silva** [relayphp/Relay.Relay#16]
I read the documentation on both projects and delved into their issue trackers in search of explanations but, apart for some minor differences (like final handlers and error middleware signatures) I see no advantage in using Relay over Stratigility.
I would be very interested in hearing the reasons you had for creating and maintaining this project instead of adopting the other one, so that I can make an informed choice on which one to adopt for my projects.

**Comment by pmjones** [comment]
Relay is a purpose-specific library, that handles only the middleware-dispatch portion. Stratigility is a significantly larger project that does quite a bit more, much of which may not be needed in some cases.

**Comment by claudio-silva** [comment]
I'm sorry, but I seem to be missing something.
From what I see on their documentation and on the project's source code, It really is nothing more than a middleware dispatcher.
I see an example where they [create a server](https://github.com/zendframework/zend-stratigility/blob/master/doc/book/usage.md) to handle requests, but even that is not done by Stratigility itself, it is using Zend\Diactoros for that, which is a separate project (which anyone can also combine with Relay to create a more complete solution).

**Comment by pmjones** [comment]
> I'm sorry, but I seem to be missing something.

I agree. They're similar but not the same; you may wish to inspect both projects more deeply, and pick which one you think suits your preferences more closely.

**Comment by mindplay-dk** [comment]
> I see an example where they create a server to handle requests, but even that is not done by Stratigility itself, it is using Zend\Diactoros for that, which is a separate project

@claudio-silva I have often wondered why Server (and a couple other things) are in zend-diactoros in the first place - IMO, it has nothing to do with PSR-7 and doesn't belong there. I don't know why it exists there and not in, say, zend-stratigility.

**Comment by claudio-silva** [comment]
@mindplay-dk I also thought that, but then I realized that the "server" is not a server, in the sense it's on, for instance, Node.js, but it's really a fancy name for a class that creates a PSR-7 server request object from PHP's global vars, calls an application-supplied handler to handle it, and then grabs the PSR-7 response object and sends it to the HTTP client.
So what we really have there is a Request factory and a Response sender.
So I guess it makes sense to put it in the same library, as it provides essential functionality for a PSR-7 implementation.

**Comment by mindplay-dk** [comment]
> So I guess it makes sense to put it in the same library, as it provides essential functionality for a PSR-7 implementation.

There's nothing essential about the functionality provided by `Server` - nothing in PSR-7 depends upon the existence for that class or anything like it.

I'd argue it creates a dependency muddiness, because plenty of packages (such as various helpers and middleware components) depend upon PSR-7, and may depend upon this package, but have no dependency upon `Server` or anything like it - if most packages dependent on PSR-7 can function perfectly without `Server`, I would argue this demonstrates that `Server` is completely outside the scope of PSR-7.

Just my opinion, but I think something like `Server` belongs in a (micro) framework (such as Expressive) and not in a PSR-7 implementation - plenty of packages depend on PSR-7 and have no dependency on `Server` whatsoever. (and if they did, their dependency would be on Diactoros, the implementation, rather than on PSR-7, the interoperability standard.)

**Comment by claudio-silva** [comment]
Packages that depend on PSR-7 do not need a concrete implementation.
Only frameworks or applications need a PSR-7 implementation. All others should just use interfaces.
The `Server` is only of use to a final application or to a framework. As those also need a PSR-7 implementation, they'll have a good use for it too, and there will be no need to install an additional package.
Of course, sometimes a middleware needs to create a new response. As there is no response factory on the PSR-7 standard, that leaves open the question of which library to use. If each middleware uses a different library for that, one gets a bloated application really fast...
But I see your point. I too prefer tightly focused libraries/packages, that only do one thing and do it well. Sometimes less is more.
If Diactoros wants to be THE PSR-7 implementation, it should refrain from providing additional functionality. That should be left to complementary packages.
I also believe there should be some standard for the creation of Response objects, so that all libraries use the same interface independent of the underlying implementation. Perhaps some other features should also be standardized. Currently there is no way to create a fully functioning HTTP pipeline based on standards only.
