### ISSUE TITLE
No access to real request object in middleware on the response's way out

### ISSUE THREAD

**Issue by KorvinSzanto** [relayphp/Relay.Relay#18]
Since `->withAttribute` and `->getAttribute` only exist on `\Psr\Http\Message\ServerRequestInterface` which is immutable, important things that need to be passed through by a middleware might not be available on the way out. 
An example of this being an issue is maybe a cookie encrypting middleware:

``` php
class CookieEncryptor
{

    use CookieEncryptingTrait, CookieDecryptingTrait, CookieSerializingTrait;

    public function __invoke($request, $response)
    {
        // Before the router
        $cookies = $this->decryptedCookies($request);
        $request = $request->withAttribute('cookies', $cookies);

        $response = $next($request, $response);
        // After the router
        // $request and $cookies may have been replaced, but we have no way to know.
        return $response->withHeader('Set-cookie', $this->serializeCookies($this->encryptedCookies($cookies->getModified())));
    }

}
```

One way to fix this is to append a reversed version of the queue onto the queue before sending a request and response, but then the middleware has to maintain state and the recommended way of catching the response on the way out becomes confusing.

Thoughts?

**Comment by pmjones** [comment]
I'm afraid I don't understand the problem. Maybe another example?

**Comment by KorvinSzanto** [comment]
Check out this modified test:

``` php
<?php
namespace Relay;

use Zend\Diactoros\ServerRequest;
use Zend\Diactoros\ServerRequestFactory;
use Zend\Diactoros\Response;

class RelayTest extends \PHPUnit_Framework_TestCase
{
    public function test()
    {
         ...
    }

    public function testRequestAttributesFallThrough()
    {
        $middlewares[] = function(ServerRequest $request, $response, $next) {
            $request = $request->withAttribute('test', false);
            $response = $next($request, $response);

            $this->assertTrue($request->getAttribute('test'), 'Request wasn\'t modified');
            return $response;
        };

        $middlewares[] = function(ServerRequest $request, $response, $next) {
            // Pass on a request object with the modified attribute
            return $next($request->withAttribute('test', true), $response);
        };

        $builder = new RelayBuilder();
        $relay = $builder->newInstance($middlewares);
        $relay(new ServerRequest, new Response);
    }

}
```

It's obvious that this test fails because the request is immutable and any changes made by the second middleware don't propagate to the first middleware. The only ways to fix this issue I can see are:
1. `$relay = $builder->newInstance($middlewares + array_reverse($middlewares));` when creating relays so that each middleware gets called twice, once on the way in and once on the way out. This has unexpected behavior with resolvers.
2. `list($request, $response) = $next($request, $response);` when calling $next, and `return [ $request, $response ];` from middleware.

**Comment by pmjones** [comment]
@mwop thoughts on this?

**Comment by pmjones** [comment]
@weierophinney thoughts on this?

**Comment by KorvinSzanto** [comment]
In concrete5, we resolve this by [requiring our middlewares return both the request and the response](https://github.com/concrete5/concrete5/blob/feature/psr-7_middleware/web/concrete/src/Http/Middleware/Pipeline/RequestPipeInterface.php#L17). Here's [an example of a middleware](https://github.com/concrete5/concrete5/blob/feature/psr-7_middleware/web/concrete/src/Http/Middleware/Concrete/SessionMiddleware.php#L44-L54), and here's [how we use it with diactoros](https://github.com/concrete5/concrete5/blob/feature/psr-7_middleware/web/concrete/bootstrap/start.php#L234-L236).

In the middleware example, returning the requests could allow us to store the session on the request object and not have any extra dependencies or state.

**Comment by weierophinney** [comment]
I'm going to flip the question around, @KorvinSzanto : Why are you using the request to communicate from nested middleware back out? What purpose does that serve?

Typically, with middleware-based approaches, the middleware should be aware of its _own request only_. If it needs to know how a lower layer processed the request, then you may want to rethink your layering, and move that logic outwards.

The message for communicating outwards is the _response_. When developing PSR-7, we did not posit attributes for responses, however, which can complicate things. As such, I'm typically seeing one of the following approaches:
- Usage of specialized headers (in other words, using headers as key/value pairs). This approach will often require an outermost middleware for stripping off any headers used for such purposes, lest they get emitted!
- A stateful object _composed_ into the various middleware that need to communicate specific state. This could be related to sessions, or it could be a request-specific storage. The problem with using such an approach is, well, state. One of the key benefits of middleware is that, if properly written, it can be stateless, which eliminates many common issues that occur in MVC stacks.

With regards to the idea of returning both the request and response, I'm a bit reluctant to use such an approach myself, as "magic array" return values are error prone and cannot be typehinted properly. If you feel it solves certain problems, however, may I suggest that you make this an object?

``` php
// from a nested middleware:
return new HttpState($request, $response);

// from a parent middleware:
$state = $next($request, $response);
if ($state->getRequest() !== $request) {
    // now check the attribute flag...
}
```

One additional problem with that approach to note, however, is that it breaks compatibility with essentially every other middleware stack currently in the ecosystem; all others I've reviewed expect middleware to return a _response_. As such, your middleware will be incompatible with any other middleware dispatchers unless a wrapper is provided.

**Comment by KorvinSzanto** [comment]
I think there's value both in having the request available in the middleware and in having the resulting request be available at the end of the relay. Another example for a reason to do this would be a caching middleware where it may be valuable to know what request object was used to render the response at the end of the relay:

``` php
<?php

/**
 * Cache middleware
 */
public function __invoke($request, $response, $next) 
{
    if ($response = $this->checkCache($request)) {
        return [ $request, $response ];
    }
    list($rendered_request, $response) = $next($request, $response);

    $this->handleCaching($rendered_request, $response, $request);
    return [ $rendered_request, $response ];
};
```

And for relays, it could be useful to run a request and response object through more than one relay:

``` php
<?php

$runner_1 = new Runner($queue_1, $resolver);
$runner_2 = new Runner($queue_2, $resolver);

list($request, $response) = $runner_1($request, $response);
list($request, $response) = $runner_2($request, $response);

return $response;
```

That said, you've given me a lot to think on with my own implementation and I appreciate that. You make some solid arguments for sticking with the patterns that exist today though I might be able to support both returning `$response` and returning `[$request, $response]` in my pipeline iterator.  
I don't want to limit interoperability, but I think that this is something that might be worth supporting. I'll spend some more time thinking on it and bring the ideas to the middleware PHP-FIG discussion when that time comes.

Thanks for the responses on this!
Korvin

**Comment by weierophinney** [comment]
@KorvinSzanto — I just remembered another approach that @pmjones and I discussed: having a stateful request attribute (an object).

``` php
// child middleware
$request->getAttribute('accumulator')->test = true;

// Parent middleware:
$accumulator = (object) ['test' => false];
$request = $request->withAttribute('accumulator', $accumulator);

$response = $next($request, $response);
if ($request->getAttribute('accumulator')->test) {
    // Changed!
}
```

It kind of flies in the face of immutability, but we specifically chose not to stipulate that all attribute values were immutable. As such, it's a valid way to pass around state if necessary, and, I'd argue, safer than accepting a changed request instance from the child.

**Comment by elazar** [comment]
^ That's how we're handling [routing in Spark](https://github.com/sparkphp/spark/blob/master/src/Handler/RouteHandler.php).

**Comment by pmjones** [comment]
@KorvinSzanto Will the @weierophinney solution salve your woes?

**Comment by KorvinSzanto** [comment]
@weierophinney in your example is there any reason to use `$request->getAttribute`? The `Request` object is immutable is there any possible way that `$request->getAttribute('accumulator') !== $accumulator`?

**Comment by weierophinney** [comment]
> is there any possible way that $request->getAttribute('accumulator') !== $accumulator?

Yes; if another layer injects a different value and passes the altered request downwards. And that's where you can begin to see the issues with state, and why you shouldn't rely on state changes from child middleware. If you need to share state, the safest approach is to do it via dependency injection instead.

**Comment by KorvinSzanto** [comment]
> Yes; if another layer injects a different value

Oh I see, you mean to say that Accumulator in this case is a mutable stateful container of some sort that we'd use to track the objects instead of storing them directly on the request. This is probably a good work around for me.

>  and passes the altered request downwards. 

Now you've lost me, from what I understand there's no possible way to alter a request and pass it down with the current stack. If a middleware deeper in the stack does `$request = $request->withAttribute('accumulator', $fake_accumulator)`, there's no way that this layer can know about that since we now have a new request object with a different set of attributes. 

The only way I can see to pass the request down the stack like this is to return `[$request, $response]` instead of `$response` as in my previous examples.

> And that's where you can begin to see the issues with state, and why you shouldn't rely on state changes from child middleware. If you need to share state, the safest approach is to do it via dependency injection instead.

This is fair, I think having a stateful container as an attribute on the request is the solution we will end up using.

That said, I don't see how in your example `$request->getAttribute('accumulator') !== $accumulator` can ever be true. Can you maybe explain that a bit better?

Best wishes,
Korvin

**Comment by weierophinney** [comment]
> Now you've lost me, from what I understand there's no possible way to
> alter a request and pass it down with the current stack. If a middleware
> deeper in the stack does $request = $request->withAttribute('accumulator',
> $fake_accumulator), there's no way that this layer can know about that
> since we now have a new request object with a different set of attributes.

I was meaning that _if_ you pass the stateful container this way, that
middleware between the originator and the final child could inject a
_different_ stateful container, which would mean that the final child would
not be changing the originator.

As an example:

``` php
// originator:
$request = $request->withAttribute('accumulator', (object) ['test' =>
false]);
$response = $next($request, $response);
// now test for the "test" property in the accumulator:
if ($request->getAttribute('accumulator', (object) ['test' =>
false])->test) {
    // will never be reached, for reasons to be explained
}

// child:
$request = $request->withAttribute('accumulator', (object) ['test' =>
false]);
return $next($request, $response);

// grandchild:
$request->getAttribute('accumulator')->test = true;
return $response;
```

In this case, the grandchild is working on the accumulator injected by the
child, instead of the one by the originator, which means that the change in
the stateful value happens on a different instance. That's what I'm getting
at.

It should rarely be an issue, but it's something to be aware of.

On Mon, Nov 2, 2015 at 3:08 PM, Korvin Szanto notifications@github.com
wrote:

> Yes; if another layer injects a different value
> 
> Oh I see, you mean to say that Accumulator in this case is a mutable
> stateful container of some sort that we'd use to track the objects instead
> of storing them directly on the request. This is probably a good work
> around for me.
> 
> and passes the altered request downwards.
> 
> Now you've lost me, from what I understand there's no possible way to
> alter a request and pass it down with the current stack. If a middleware
> deeper in the stack does $request =
> $request->withAttribute('accumulator', $fake_accumulator), there's no way
> that this layer can know about that since we now have a new request object
> with a different set of attributes.
> 
> The only way I can see to pass the request down the stack like this is to
> return [$request, $response] instead of $response as in my previous
> examples.
> 
> And that's where you can begin to see the issues with state, and why you
> shouldn't rely on state changes from child middleware. If you need to share
> state, the safest approach is to do it via dependency injection instead.
> 
> This is fair, I think having a stateful container as an attribute on the
> request is the solution we will end up using.
> 
> That said, I don't see how in your example $request->getAttribute('accumulator')
> !== $accumulator can ever be true. Can you maybe explain that a bit
> better?
> 
> Best wishes,
> Korvin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/relayphp/Relay.Relay/issues/18#issuecomment-153157078
> .

## 

Matthew Weier O'Phinney
matthew@weierophinney.net
https://mwop.net/

**Comment by KorvinSzanto** [comment]
Ah I see what you mean now.
I really appreciate the extra explanation on these things, I want to make sure that what I end up with is as standard as possible. It's really valuable to me to work through these cases to make sure that I truly have a good understanding of the problems I'm solving and the solutions I'm providing.

Thanks everyone!
Korvin

**Comment by alexindigo** [comment]
@KorvinSzanto and for those who find it later, you can supply "Middleware Terminator" function as the last middleware in the chain. It would work instead of their built-in middleware terminator and your custom one can return both Request and Response as an array.
