### ISSUE TITLE
Please Review 2.x

### ISSUE THREAD

**Issue by pmjones** [relayphp/Relay.Relay#20]
@mindplay-dk @elazar @renan @KorvinSzanto @shadowhand --

As noted in #17, we needed to modify the middleware interface signature, but it was a BC break, thus making a major version bump necessary.

The new BC-breaking middleware interface is now in the 2.x branch.  I have added some other non-BC-breaking changes, such as the run() methods that Rasmus wanted, and a Last middleware class instead of an embedded closure. Please review and test the changes; now is your chance to speak your mind, or forever hold your peace!

**Comment by elazar** [comment]
Linkage: https://github.com/relayphp/Relay.Relay/compare/1.x...2.x

**Comment by elazar** [comment]
@pmjones No issues jumping out at me. :+1: relayphp/Relay.Middleware#12 next? :wink:

**Comment by KorvinSzanto** [comment]
:+1: Looks good to me

**Comment by shadowhand** [comment]
The `Last` class is missing a `@param` descriptor for `$next`

**Comment by pmjones** [comment]
@shadowhand fixed, thanks!

**Comment by shadowhand** [comment]
And is `Last` even necessary? It seems pointless, since the primary concern is being able to overload the very last resolver, which you've already done by defining a `protected last() : callable` method. Since the `Last` class is not resolved or injected, it is no different than returning a closure.

**Comment by pmjones** [comment]
At the very worst, it's a proof for the MiddlewareInterface.

**Comment by shadowhand** [comment]
Seems like noise to me, but okay. Everything else looks okay.

**Comment by shadowhand** [comment]
Oh wait, one other thing...

**Comment by shadowhand** [comment]
Type hinting against `RequestInterface` is not necessarily enough in many situations and will require hinting against `ServerRequestInterface`. How do you propose we resolve that without running into strict mode errors regarding the signatures not matching?

**Comment by pmjones** [comment]
(/me furrows brow)

ServerRequestInterface satisfies RequestInterface, and AFAIK using a ServerRequestInterface instance there does not cause anything to blow up. What am I not seeing?

**Comment by shadowhand** [comment]
@pmjones some middleware requires methods only available to `ServerRequestInterface` and type hinting against `RequestInterface` does not ensure those methods exist.

**Comment by pmjones** [comment]
/me ponders

The interfaces are entirely optional, and are there only for formality.  Really all that's needed is callables; the arguments are never really checked.

With that in mind, I have no objection to converting the exsting MiddlewareInterface to ClientMiddlewareInterface, and adding a new ServerMiddlewareInterface that typehints to ServerRequestInterface.  One added benefit here is to show the intended use for the various middlewares.

Thoughts?

**Comment by elazar** [comment]
I'd be fine with that, though there's no reason the existing MiddlewareInterface can't remain as-is for code that doesn't need the added level of specificity.

**Comment by shadowhand** [comment]
@pmjones I don't think that's entirely necessary, I just thought I would voice the thought before you tagged a release. For the (very few) middleware that require it, we can do an explicit check.

**Comment by pmjones** [comment]
I'd rather leave the existing MiddlewareInterface as it is, then, since it covers both the server and the client cases. Again, @shadowhand, if you think I'm missing something about what you're saying, please let me know.

**Comment by renan** [comment]
The changes looks great! Thank you for looking into it @pmjones

**Comment by shadowhand** [comment]
I'd love to see this be released!

**Comment by Isinlor** [comment]
Great package! I'm also looking forward for this to be released. If there is anything else to do before release I'm happy to help.

**Comment by mindplay-dk** [comment]
Hmm, [this](https://github.com/relayphp/Relay.Relay/blob/2.x/src/MiddlewareInterface.php#L37) looks wrong?

The third argument being passed to a middleware function is not itself middleware - it's a _delegate_ to middleware, which does not have the same signature as actual middleware, e.g. does not have a third argument `$next`, since that logic is handled [here](https://github.com/relayphp/Relay.Relay/blob/2.x/src/Runner.php#L73), and the call signature of `__invoke()` of `$this` defined [three lines above it](https://github.com/relayphp/Relay.Relay/blob/2.x/src/Runner.php#L69) does not accept a third argument.

Am I wrong?

**Comment by mindplay-dk** [comment]
Oh, PS, I know _I'm_ the one who proposed that interface ;-)

**Comment by mindplay-dk** [comment]
Probably this is the correct way to document that interface:

``` php
interface MiddlewareInterface
{
    /**
     * @param RequestInterface  $request  the request
     * @param ResponseInterface $response the response
     * @param callable          $next     delegate function to dispatch the next middleware component:
     *                                    function (RequestInterface $request, ResponseInterface $response): ResponseInterface
     *
     * @return ResponseInterface
     */
    public function __invoke(RequestInterface $request, ResponseInterface $response, callable $next);
}
```

Man, PHP desperately needs type-checking for closure signatures to avoid this kind of mess - or at the very least a php-doc standard for it... in absence of that, I put the function signature in the comment of the `@param` so it's at least more formally documented for humans...

**Comment by pmjones** [comment]
>  I know I'm the one who proposed that interface ;-) ... Probably this is the correct way to document that interface ...

You broke it, you fix it! ;-) No, more seriously, if you want to send a PR that would help immensely.

**Comment by pmjones** [comment]
@mindplay-dk --

>  I know I'm the one who proposed that interface ;-) ... Probably this is the correct way to document that interface ...

You broke it, you fix it! ;-) No, more seriously, if you want to send a PR that would help immensely.

**Comment by mindplay-dk** [comment]
Sorry, I don't use relay anymore - but you can plunk the updated interface from [my own lib](https://github.com/mindplay-dk/middleman/blob/master/src/MiddlewareInterface.php).

**Comment by mindplay-dk** [comment]
(actually that makes me wonder again if this middleware interface really ought to reside in a PSR? people talk of "PSR-7 middleware" but that's never strictly speaking been a "thing"...)

**Comment by Isinlor** [comment]
[It's about a half-year from the last discussion about middleware on FIG.](https://groups.google.com/forum/#!topic/php-fig/_idBxaLoapY). During that time 3 biggest middelware based projects (Slim, Zend-Expressive and Relay) reached stable releases. Maybe it's good time to start discussion about PSR-Middleware again? It will be probably a year or so anyway before such PSR would be accepted.

Also I submitted pull-request with fixes to the documentation. Do they look OK?

**Comment by odan** [comment]
When will version 2.x be released?

**Comment by pmjones** [comment]
All -- the PHP-FIG is considering the entrance of a middleware proposal. I figure that it would be best to postpone further work on 2.x until that proposal is accepted or rejected; or, to coordinate 2.x work with the proposal discussions. Sorry for the delay.

**Comment by pmjones** [comment]
Closing this until the FIG middleware proposal is accepted or rejected. A 2.x version may or may not adopt it.
