### ISSUE TITLE
RelayBuilder does not allow iterators to be used

### ISSUE THREAD

**Issue by shadowhand** [relayphp/Relay.Relay#21]
The current [array check in `RelayBuilder`](https://github.com/relayphp/Relay.Relay/blob/277638ddafe184550d9c2441c23dd911d605a5ce/src/RelayBuilder.php#L94-L105) is not robust and will fail for any number of other iterator types, such as classes that implement `Iterator` but do not use `ArrayObject`.

**Comment by elazar** [comment]
:+1:

**Comment by pmjones** [comment]
This is likely a subtle BC break for 1.x. Any objection to submitting a PR against 2.x. ? It would also allow removing the GetArrayCopy interface.

**Comment by shadowhand** [comment]
It is not a break in functionality. ArrayObject will continue to work as before, since ArrayObject implements Traversable.
