### ISSUE TITLE
Relay type hint against RequestInterface is fragile

### ISSUE THREAD

**Issue by shadowhand** [relayphp/Relay.Relay#25]
[This type hint](https://github.com/relayphp/Relay.Relay/blob/e835fc45351b7a92a6fdf2a36be7bd59ef56c8ae/src/Relay.php#L13) will not work with many middlewares that require [`ServerRequestInterface`](http://www.php-fig.org/psr/psr-7/#3-2-1-psr-http-message-serverrequestinterface) for things like query strings, uploaded files, etc.

I don't think there is any particular use for Relay that would make sense with `RequestInterface` since that interface is meant to represent a request for an external resource.

The most annoying thing is that if you are using an automatic injection system the only way to provide the correct interface for execution is to alias `ServerRequestInterface` to `RequestInterface`, which is less than ideal.

**Comment by pmjones** [comment]
Agreed. It occurred to me earlier to support client middlewares via a separate interface. We can make it happen in 2.x, since it is not yet released.

**Comment by shadowhand** [comment]
PR created.

**Comment by shadowhand** [comment]
Oddly enough, all of the middleware in Relay.Middleware was already using `ServerRequestInterface`.

**Comment by pmjones** [comment]
Fixed by #26
