### ISSUE TITLE
Stock Runner should ensure middleware return is ResponseInterface

### ISSUE THREAD

**Issue by ralphschindler** [relayphp/Relay.Relay#27]
https://github.com/relayphp/Relay.Relay/blob/2.x/src/Runner.php#L66-L74

Since middleware is contributed code, it is being left up to the contributor to ensure they are returning a `Psr\Http\Message\ResponseInterface`.  Runner should at least type-check the return of the middleware and throw an exception before passing the return value along to another middleware.  Not doing this causing exceptions and PHP errors to bubble up later in the call chain, making the resolution non-obvious to the developer writing the middleware ("Did you forget to return a Response in **Middleware**?").

**Comment by pmjones** [comment]
PRs welcome! 8D (Sorry could not resist. ;-)

Yes, I think that's a reasonable thing to check. Thanks for this. If you _do_ get around to a PR, I'll merge it, so you get automatic credit, otherwise I'll add it myself. Thanks!

**Comment by pmjones** [comment]
Fixed by #28
