### ISSUE TITLE
yeild $next like koajs?

### ISSUE THREAD

**Issue by pqr** [relayphp/Relay.Relay#3]
Have you seen Koa - Node.js framework with middleware-pipeline http://koajs.com/
They use "yield next" - what do you think?

**Comment by pmjones** [comment]
Interesting! I confess I can't see a big difference in operation, though. The examples on the KoaJS site didn't really help me understand the advantages of `yield` over `return`. Can you provide some PHP-specific examples, perhaps involving a modification to the Radar.Adr handlers? https://github.com/radarphp/Radar.Adr/tree/1.x/src/Handler

**Comment by pqr** [comment]
I remember I saw yield-style php framework inspired by koa.js somewhere on github. Now I searched it: https://github.com/gigablah/durian

and explanation presentation: http://www.slideshare.net/KuanYenHeng/durian-a-php-55-microframework-with-generatorstyle-middleware

**Comment by sagikazarmark** [comment]
Seems like an interesting idea. I read the presentation and I saw some really interesting explanations about why it is good.

However I have some problem with it as well and the author of that presentation forgot to mention the downsides of this solution: context.

In current middleware implementations (relay, stack) context travels through the middleware stack and it does not get affected by any context. However the mentioned microframework binds the context to generators which does not seem good to me.

**Comment by pmjones** [comment]
Yeah, I missed the "context" thing on first reading, and on subsequent readings it seemed at odds with the existing Relay implementation. It changes the signature quite a bit.
