### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by martinssipenko** [relayphp/Relay.Relay#36]
There have been no updates on this since February 2018, is this project dead or we could expect a stable 2.0 any time soon?

**Comment by kevinsmith** [comment]
I was curious about this as well. I've used it on small example projects, and it's working quite well. Anything I can do to help get 2.0 ready for release, @pmjones?

**Comment by martinssipenko** [comment]
There was an alpha release on Feb 13 - https://github.com/relayphp/Relay.Relay/releases/tag/2.0.0-alpha1

**Comment by kevinsmith** [comment]
Release candidate out now: [2.0.0-rc.1](https://github.com/relayphp/Relay.Relay/releases/tag/2.0.0-rc.1)

If no issues come up in the next week or so, it'll be the first stable 2.0.0 release.

**Comment by kevinsmith** [comment]
[2.0 is released!](https://github.com/relayphp/Relay.Relay/releases/tag/2.0.0)
