### ISSUE TITLE
Changing Project Name

### ISSUE THREAD

**Issue by pmjones** [relayphp/Relay.Relay#4]
@andersonamuller @badlamer @bradleyboy @byoigres @calvinfroedge @clickalicious @coderabbi @coldwinds @cwscribner @davidpersson @dbonner1987 @dolfelt @elazar @FallingBullets @ferceg @garrettw @gsahr @hkulekci @hmert @hossein- @jakejohns @jensscherbl @jessupdw @johnutzm @jpcercal @khanhicetea @KingCrunch @koriym @lifesign @lku @markstory @mcrumm @Meroje @mikedfunk @mkraemer @nikolay @ojhaujjwal @pqr @ronanguilloux @shameerc @shyuan @silentworks @texdc @tuupola @websoftwares @wsuff @xduh @ytake @zanderbaldwin

tl;dr: I'll be renaming "Pipeline" to "Relay" in the near future. Read on for details.

---

Naming is one of the two hard things in programming.*

A commenter on Reddit pointed out that Pipeline doesn't actually implement the ["pipeline" design pattern](http://en.wikipedia.org/wiki/Pipeline_%28software%29). I did look up that pattern before settling on the name, but my cursory review was insufficient. It turns out that the libary implementation is not really close enough to the pattern to be called a pipeline proper. As such, there is reason to believe programmers familiar with the pattern will be confused and/or irritated by the name.

To avoid diffusing the term "pipeline", and to honor my own desire for common vocabulary (_cough_ Facade _cough_), I'll be renaming the project to "Relay."  I have discovered no existing software design pattern of that name, and no other PHP project of that name. It does seem to convey the underlying operation of the libary (each request is relayed to the next middleware, and each response is relayed back in turn).

The plan is to rename the Github organization from "pipelinephp" to "relayphp", the site from "pipelinephp.com" to "relayphp.com", the library from "Pipeline.Pipline" to "Relay.Relay", the underlying classes from `Pipeline*` to `Relay*`, and the composer pacakge from "pipeline/pipeline" to "relay/relay". All your existing Github forks and checkouts should continue to work, but you will need to update your composer.json files.

I expect to accomplish this later today or early tomorrow. I will update this issue when it's done.

My apologies for having done insuffient research in the first place, and for this ensuing hassle. Thank you for your patience with this early-stage project.

(\* The others are cache-clearing and off-by-one errors.)

**Comment by silentworks** [comment]
I fear there will be a name clash with Facebook Relay when its is released, I would suggest staying with current name or choose another that is not Relay.

Here is a link with some background on the Facebook project https://gist.github.com/wincent/598fa75e22bdfa44cf47

**Comment by elazar** [comment]
I'm indifferent on that particular issue, though I will note that the [React](http://reactphp.org/) PHP project may have suffered a bit when Facebook subsequently released its own [React](https://facebook.github.io/react/) JS library.

**Comment by dolfelt** [comment]
Thanks for keeping us updated. I'm about to integrate it with [Spark](https://github.com/sparkphp/Spark), so I'll just make sure to update that.

@silentworks @elazar Names are always going to conflict. I think Relay is very descriptive of what it's doing. Shall we just call it MiddlewarePHP? :wink:

**Comment by silentworks** [comment]
My point is more inline with what @elazar mentioned, this project could get lost or more difficult to find when Facebook releases their Relay framework and if they should release a PHP library with it, it would be even more confusing.

**Comment by dolfelt** [comment]
@silentworks I can definitely see that happening. Any other name suggestions? I agree with @pmjones about renaming it from Pipeline if it conflicts with an already defined programming concept.

**Comment by elazar** [comment]
Tough call. [StackPHP](http://stackphp.com/) has kind of already established a foothold for itself as a middleware library, at least where Symfony 2's http-kernel core is concerned.

I agree that Relay is a descriptive enough name to be distinctive from other libraries in the middleware space, and that perpetuating misnomers with naming should be avoided where possible.

I can't say for certain what impact Facebook's React library had on the React PHP project. And really, I'm not even certain popularity or ease of location are substantial enough issues to be a factor.

@pmjones can correct my view if it's inaccurate, but historically, I think projects where he's lead the charge have had a modest but passionate following, and I don't consider that to be a bad thing.

**Comment by pmjones** [comment]
It looks like the Facebook Relay is for JS; if that's true, I think the different language (as vs PHP) is enough to deconflict.

**Comment by jensscherbl** [comment]
@pmjones Just curious, why is this a separate thing and not an Aura 3.x package?

**Comment by pmjones** [comment]
@jensscherbl -- I considered making it an Aura.Dispatcher 3.x package, and later as a new Aura package of its own. In the end, I thought it might be more approachable as something separate from Aura, with its own community drawn from a wider array of folks, especially when it comes to sharing middleware pieces.

**Comment by dolfelt** [comment]
I think that's a smart choice @pmjones. :+1:

**Comment by pmjones** [comment]
Everyone, the project name has now been changed from "pipelinephp" to "relayphp". Please update links accordingly; cf. https://help.github.com/articles/changing-a-remote-s-url/

**Comment by pmjones** [comment]
All right, I believe all the names have been updated. "pipelinephp.com" shows a 404, as does "relayphp.github.io", but "relayphp.com" does appear to show up properly. I will contact the Github folk about the latency in the domain names.

Again, thanks for your patience and support.

**Comment by pqr** [comment]
Oh no :(
Facebook's Relay is not only the JS library, but the concept of pulling data from server to client side React components. And we all know that Facebook historically connected with PHP.
Now, I am 100% sure that anyone who heared about Facebook's Relay and see "relayphp" will think: "Waht a wonderfull day - Facebook released server side of their Relay infrastructure! let me have a look... wait a moment... wtf??"

So you will get over 9000 new visitors on this repository - good for marketing, but stil confusing.

**Comment by pmjones** [comment]
@pqr: I get your dismay here. Even so, Facebook React and the ReactPHP project don't seem to have that kind of conflict; that makes it harder for me to imagine a conflict over the name Relay.

**Comment by pqr** [comment]
@pmjones ReactPHP - good example, did not think about it. But who knows how many ReactPHP repository visitors were confused because they were looking for "ReactJS in PHP"?)
Ok, anyway, let us move forward with Relay.Relay and concetrate on it's development! I am personally looking forward

**Comment by davidianbonner** [comment]
@pmjones seconded. 

Until such times as facebook actually release the Relay framework to the public, I wouldn't expect there to being any real amount of confusion worth worrying about by using relayphp.

**Comment by silentworks** [comment]
@pmjones can you close this out please as I think you have changed the name already and no further need to have this open.
