### ISSUE TITLE
2.x $next isn't callable

### ISSUE THREAD

**Issue by urugator** [relayphp/Relay.Relay#41]
Documentation suggests that `$next` is callable, but the `$next` is always a `Runner` instance, which doesn't implement `__invoke`
```php
function (
    Request $request, // the request
    callable $next // the next middleware or handler
) : Response {
    // ...
}
```

**Comment by kevinsmith** [comment]
Hmm, you're right. Seems like that must have been in the plans for the original maintainer but was never removed from the docs when the feature was scrapped.

Is this something you'd benefit from? I'm trying to imagine the scenario where it would make much of a difference.

**Comment by urugator** [comment]
I have returned to php after some time and wanted to try more functional approach.
However I quickly gave up, because there is no autoloading for functions and closures can't be named, which doesn't help with debugging.
So with the current state of things, sticking with standard `$next->handle($request)` is preferrable.
However I suggest to add this call to docs, because people coming from eg `express/koa` are quite used to `next()` and currently such call won't fail, it just doesn't return request object, so it's not immediately clear what's wrong.

**Comment by mtils** [comment]
The benefit is to be not forced to write PSR-15 middlewares. And the overhead to implement a __invoke() method in Runner is basically zero. I would rate this up. (While not using relay to be honest...)

**Comment by urugator** [comment]
@mtils The overhead comes in the form of ambiguity - more ways to do the same thing - loosen type checking, docs has to explain more etc...

I ended up with own PSR-15 impl (for different reasons). It doesn't support callables directly, but exposes:

```php
class GenericMiddleware implements MiddlewareInterface {
  private $middleware;

  function __construct(callable $middleware) {
    $this->middleware = $middleware;
  }

  public function process(ServerRequestInterface $request, RequestHandlerInterface $next): ResponseInterface {
    return ($this->middleware)($request, $next);
  }
}
```

**Comment by mtils** [comment]
Yes I understand. This is a design decision, I would want to have less type safety here, others more which is totally understandable. In case of relay it explains itself to support callables. So either it should only support PSR-15 middlewares (in Runner) or allow callables (and implement __invoke()).
But at least it should be removed from the readme.

**Comment by duzun** [comment]
I don't see why not just add the `__invoke` method and provide the documented functionality? It is a trivial method to implement but allows for better flexibility, where non-PSR-15 middlewares are used.

I ended up with an extended class of `Relay\Runner`, which has only this method:
 
```php
    public function __invoke(ServerRequestInterface $request) : ResponseInterface
    {
        return $this->handle($request);
    }
```

Why not just add it to the `Relay\Runner`?

**Comment by kevinsmith** [comment]
I agree, I see no reason not to add support, especially since the documentation already advertises it. There is some ambiguity, as @urugator noted, but the benefit seems to outweigh the cost here.

**Comment by kevinsmith** [comment]
And to keep everything together, noting here that when this feature is implemented, I need to improve the error reporting mentioned at https://github.com/relayphp/Relay.Relay/pull/43#issuecomment-500202529.

**Comment by kevinsmith** [comment]
Anyone interested, would you mind having a look at #45 to see if that resolves this for you? Let's move any conversation on this issue to that PR.
