### ISSUE TITLE
Help: migrate from Relay 1 to Relay 2?

### ISSUE THREAD

**Issue by cj-clx** [relayphp/Relay.Relay#50]
I've got an application which is currently using Relay 1.x.  I'd like to migrate it to Relay 2.x as part of wider modernization of that app.

Any chance someone could briefly outline the changes needed, or point me at resources that would help?

**Comment by kevinsmith** [comment]
Unfortunately the method signatures for double-pass (Relay v1) and single-pass (Relay v2) middleware are incompatible, so there's no easy way to use a converter or automate the change. (Without losing the response anyway.)

For any third-party middleware, you'll just need to look for PSR-15 compatible alternatives. Here's a couple great resources:

- https://github.com/middlewares/awesome-psr15-middlewares
- https://packagist.org/search/?tags=psr-15

For custom middleware, you'll need to refactor to use the new single-pass method signature instead. To give you a better idea of what that might look like, here's a good example of both methods of middleware for the same underlying package:

- Double-pass: https://github.com/oscarotero/psr7-middlewares/blob/c3e223c4a2603eda27a6b714e657ec0990c2a0ee/src/Middleware/Cors.php#L195-L231
- Single-pass: https://github.com/middlewares/cors/blob/04bbfe7c8d79a16628920191b968b46b5c82ee8c/src/Cors.php#L37-L56

Hope this helps!
