### ISSUE TITLE
Tagging latest release

### ISSUE THREAD

**Issue by wirebox-platform** [relayphp/Relay.Relay#52]
Hey there
Since the last issue was merged, i've not seen a tag that contains this yet. Is this something you'll do or something I have to do myself?
Just so that i'm not adding odd dependency constraints to all my projects :)

Cheers

**Comment by kevinsmith** [comment]
Hey @wirebox-platform, sorry it took so long to respond. I've had some personal things to deal with lately. And my apologies on failing to tag this release! I'll jump on that today.

**Comment by kevinsmith** [comment]
Done! https://github.com/relayphp/Relay.Relay/releases/tag/2.1.0
